### ISSUE TITLE
Website or wiki?

### ISSUE THREAD

**Issue by taylorjwright** [asjadnaqvi/Diff-in-Diff-Notes#1]
Riffing on the "port to website" in the README TODO, maybe we should think about whether it would be better to structure it as wiki? That said, I don't really know how much more difficult that might be to do than a standard static website (which is the extent of my experience). 

The World Bank's Development Impact Evaluation (DIME) has a [wiki](https://dimewiki.worldbank.org/) that might be nice to help visualize what it could look like.

Another idea is maybe folding things into Nick Huntington-Klein's [Library of Statistical Techniques](https://lost-stats.github.io/)? Or do you think having just a dedicated website/wiki for DiD would be more useful?

**Comment by asjadnaqvi** [comment]
I like the LOST setup but this needs something simpler. I will add a section on Stata code so it will be great if that can be sectioned from the setup. If you want to jump in to sort this out please feel free to do so! I won't be able to do much on this end till I get some free chunk of time.

**Comment by taylorjwright** [comment]
As long as it's cool that there will be R code as well, I don't want to start a war on here seeing as you're responsible for bringing a bunch of these methods to Stata :P 

I'm on the market this year so time is a little tight here but I can certainly contribute whenever possible! When you say "jump in and sort this out" do you mean starting on the website/researching how building a wiki might work (just want to know what I should work on when I have time to do so)?

**Comment by asjadnaqvi** [comment]
I am fine with R :) I just don't use it! So if you want to setup an R section it is fine with me.

Regarding the website stuff, I would just fill up the readme for now and sort it out later. As long as the stuff is sectioned out, it can be partitioned easily later in some Jekyll theme. So this is low priority for me right now.

Also good luck with the job market!

**Comment by taylorjwright** [comment]
Perfect, that makes sense. 

And thank you!

**Comment by asjadnaqvi** [comment]
OK. I have added you as a contributor. Just add stuff at your leisure.
