### ISSUE TITLE
Example code and videos

### ISSUE THREAD

**Issue by taylorjwright** [asjadnaqvi/Diff-in-Diff-Notes#2]
Just a comment to say that as part of my reading group I've been trying to hold a session afterwards where we go over the code associated with each paper. I have a [GitHub repo](https://github.com/taylorjwright/did_reading_group) for them but some haven't been pushed yet. 

I use two running examples: 
1. [Hoekstra and Cheng (2012)](http://jhr.uwpress.org/content/48/3/821.short) because that's what Scott Cunningham uses in his Mixtape.
2. [Stevenson and Wolfers (2006)](https://academic.oup.com/qje/article-abstract/121/1/267/1849020?redirectedFrom=fulltext) because I thought it would be nice to continue Andrew Goodman-Bacon's example from his paper which is usually a first introduction to this literature. 

The plan is to eventually create a short Youtube video for each one going through the scripts.

**Comment by asjadnaqvi** [comment]
A cool! Thanks for sharing. I can link to these as well once they are made public.
